### ISSUE TITLE
root-level hooks are not being called partially fixed ref : #39

### ISSUE THREAD

**Issue by tsdaita** [mmotkina/mocha-parallel-tests#41]
Hi,
Apologies for the late response wrt issue #39 . Thanks for taking a look and fixing it.
Appears this is partially fixed. When passing the individual file ( node_modules/.bin/mocha-parallel-tests tests/sample.js) it seems to work.
But if we give just the dir path (either node_modules/.bin/mocha-parallel-tests tests/ or node_modules/.bin/mocha-parallel-tests tests/*.js) it does not seem to call the root level hooks.

**Comment by 1999** [comment]
@tsdaita can you give a more detailed example? A failing test would be even better

**Comment by tsdaita** [comment]
The same code provided in the #39 can be used. 
When passing the folder (node_modules/.bin/mocha-parallel-tests tests/ ) where both the test file and global hook file are present it does not print the statement from "base : before run!" from the base.js

**Comment by 1999** [comment]
Did you update mocha-parallel-tests to the latest version? The test [here](https://github.com/mmotkina/mocha-parallel-tests/tree/master/test/global-hooks-require) is exactly about your situation and it was fixed.

**Comment by tsdaita** [comment]
Hi,
Using the same set of files that I have provided in issue #39, and after
installing the updated version I still see the issue of the global hook not
being called when I pass the folder name. Here is the output.

%>npm install mocha-parallel-tests

└── mocha-parallel-tests@0.5.1  extraneous

Scenario 1:

When invoking the command by passing the actual test file, you can observe
that the print statement from the global hook file is being printed.

%>./node_modules/mocha-parallel-tests/dist/bin/mocha-parallel-tests
tests/sample.js

base : before run!    /*** THIS from the base.js ***/


  An afterEach hook

before run!

nested before run!

    in some nested contexts

nested it run!

afterEach run!

      ✓ runs after this block

second nested it run!

afterEach run!

      ✓ runs again after this block

  2 passing (16ms)


Scenario 2:

Now invoking the command by passing the folder containing the tests, you
can observe that the print statement from the global hook file is not being
printed.

%> ./node_modules/mocha-parallel-tests/dist/bin/mocha-parallel-tests tests/



  An afterEach hook

before run!

nested before run!

    in some nested contexts

nested it run!

afterEach run!

second nested it run!

      ✓ runs after this block

afterEach run!

      ✓ runs again after this block

  2 passing (24ms)

**Comment by 1999** [comment]
Oh, got it! The problem is about tests path. Will fix this in #42

**Comment by 1999** [comment]
Check out `mocha-parallel-tests@0.5.2`
There's only one exception: console logs are not shown yet: https://github.com/mmotkina/mocha-parallel-tests/pull/43

@tsdaita
